### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'replace'

### ISSUE THREAD

**Issue by 3eLepyKa** [akpw/mktxp#19] opened 2022-01-25 07:01 UTC
when trying to output data from the router, the connection crashes

> Traceback (most recent call last):
  File "/usr/lib/python3.9/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.9/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.9/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.9/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.9/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.9/http/server.py", line 415, in handle_one_request
    method()
  File "/home/antioh/.local/lib/python3.9/site-packages/prometheus_client/exposition.py", line 219, in do_GET
    status, header, output = _bake_output(registry, accept_header, params)
  File "/home/antioh/.local/lib/python3.9/site-packages/prometheus_client/exposition.py", line 85, in _bake_output
    output = encoder(registry)
  File "/home/antioh/.local/lib/python3.9/site-packages/prometheus_client/openmetrics/exposition.py", line 32, in generate_latest
    ['{}="{}"'.format(
  File "/home/antioh/.local/lib/python3.9/site-packages/prometheus_client/openmetrics/exposition.py", line 33, in <listcomp>
    k, v.replace('\\', r'\\').replace('\n', r'\n').replace('"', r'\"'))
AttributeError: ("'NoneType' object has no attribute 'replace'", Metric(mktxp_system_uptime, Time interval since boot-up, gauge, , [Sample(name='mktxp_system_uptime', labels={'version': '7.1.1 (stable)', 'board_name': 'RB5009UG+S+', 'cpu': None, 'architecture_name': 'arm64', 'routerboard_name': 'main5009', 'routerboard_address': '10.0.0.1'}, value=757713.0, timestamp=None, exemplar=None)]))

mktxp 0.34
prometheus_client 0.12
router rb5009 ros 7.1.1

**Comment by akpw** [comment] 2022-09-18 09:52
seems to be a duplicate of #22, let's follow up there

**Closed by akpw** 2022-09-18 09:52 UTC
