### ISSUE TITLE
UTF-8 decode error

### ISSUE THREAD

**Issue by preisi** [akpw/mktxp#47] opened 2022-10-28 10:59 UTC
I can't get mktxp to work with my RB5009 and RouterOS v7.3.1. The culprits seem to be an error during encoding the router's response(?) after having established a connection and missing commands?

```
$ mktxp export
Connecting to router RB5009@192.168.178.1
2022-10-28 13:05:32 Connection to router RB5009@192.168.178.1 has been established
2022-10-28 13:05:32 Running HTTP metrics server on port 49090
Error getting dhcp info from routerRB5009@192.168.178.1: 'utf-8' codec can't decode byte 0xb2 in position 6: invalid start byte
Error getting PoE info from routerRB5009@192.168.178.1: ('Error "no such command prefix" executing command b\'/interface/ethernet/poe/print .tag=42\'', b'no such command prefix')
Error getting caps-man remote caps info from routerRB5009@192.168.178.1: 'utf-8' codec can't decode byte 0xb2 in position 6: invalid start byte
Error getting dhcp info from routerRB5009@192.168.178.1: 'utf-8' codec can't decode byte 0xb2 in position 6: invalid start byte
----------------------------------------
Exception occurred during processing of request from ('10.10.10.2', 48734)
Traceback (most recent call last):
  File "/usr/lib/python3.9/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.9/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.9/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.9/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.9/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.9/http/server.py", line 415, in handle_one_request
    method()
  File "/opt/mikrotik-exporter/virtualenv/lib/python3.9/site-packages/prometheus_client/exposition.py", line 278, in do_GET
    status, headers, output = _bake_output(registry, accept_header, accept_encoding_header, params, False)
  File "/opt/mikrotik-exporter/virtualenv/lib/python3.9/site-packages/prometheus_client/exposition.py", line 104, in _bake_output
    output = encoder(registry)
  File "/opt/mikrotik-exporter/virtualenv/lib/python3.9/site-packages/prometheus_client/openmetrics/exposition.py", line 21, in generate_latest
    for metric in registry.collect():
  File "/opt/mikrotik-exporter/virtualenv/lib/python3.9/site-packages/prometheus_client/registry.py", line 97, in collect
    yield from collector.collect()
  File "/opt/mikrotik-exporter/virtualenv/lib/python3.9/site-packages/mktxp/flow/collector_handler.py", line 36, in collect
    yield from collect_func(router_entry)
  File "/opt/mikrotik-exporter/virtualenv/lib/python3.9/site-packages/mktxp/collector/capsman_collector.py", line 57, in collect
    BaseOutputProcessor.augment_record(router_entry, registration_record, dhcp_lease_records)
  File "/opt/mikrotik-exporter/virtualenv/lib/python3.9/site-packages/mktxp/flow/processor/output.py", line 36, in augment_record
    dhcp_lease_record = next((dhcp_lease_record for dhcp_lease_record in dhcp_lease_records if dhcp_lease_record.get('mac_address')==registration_record.get('mac_address')))
TypeError: 'NoneType' object is not iterable
```

I'm using the latest mktxp version 0.38 according to `mktxp info`. If I can provide any further information, please let me know.

**Comment by akpw** [comment] 2022-10-28 11:42
@preisi there were a few encoding-related issues reported, such as #14 and [#68](https://github.com/socialwifi/RouterOS-api/issues/68) -- the root cause seemed outside mktxp, and suggested workaround was either changing the characters in your routers' fields (comments etc) or, alternatively, changing the local copy of the [routeros-api library](https://github.com/socialwifi/RouterOS-api)

regarding the POE error, does the Mikrotik device in question supports POE? You can check via 
```
/ interface ethernet poe print
```
and if not, just disable POE via setting ```poe = Failse``` in the mktxp.conf file

**Comment by preisi** [comment] 2022-10-28 12:24
First of all thanks for the quick and helpful response!

> @preisi there were a few encoding-related issues reported, such as #14 and [#68](https://github.com/socialwifi/RouterOS-api/issues/68) -- the root cause seemed outside mktxp, and suggested workaround was either changing the characters in your routers' fields (comments etc) or, alternatively, changing the local copy of the [routeros-api library](https://github.com/socialwifi/RouterOS-api)

That was a good pointer, too. Seems that a hostname in my network is problematic ("hap ac²"). In this case I could change it to make everything work, but this is obviously no permanent solution, I cannot control every device in my network and this can happen again any time. I'll take a look into the routeros-api (on the first look it seems rather dead :()

> regarding the POE error, does the Mikrotik device in question supports POE?

It actually didn't >.< I didn't even think about checking that. -> I disabled it, that error is gone now. Typical PEBMAC.

**Comment by M0r13n** [comment] 2022-10-31 13:26
The underlying cause is that mktxp relies on [RouterOS-api](https://github.com/socialwifi/RouterOS-api) as a wrapper around the API. But this projects seems abandoned since 2019. Therefore, we can not patch the root cause of the encoding error.

The RouterOS-api implicitly assumes that the API response is UTF-8 encoded. But Mikrotik uses latin-1 as the encoding.

**Comment by M0r13n** [comment] 2022-10-31 13:48
@akpw I created a patch for this flaw. Admittedly, this is not the cleanest option. But since we can't fix the upstream dependency this solution seems to be sufficient.

**Comment by akpw** [comment] 2022-11-07 06:40
@M0r13n thanks for the patch, not the cleanest option indeed but way better than working around the issue on the router side

**Comment by akpw** [comment] 2022-11-07 06:43
> I'll take a look into the routeros-api (on the first look it seems rather dead :()
@preisi thanks for taking a look there. if possible, do you think you can try to submit a pull request for the library? 
(maybe it's less dead than it seems, one way to find out :)

**Comment by akpw** [comment] 2022-11-26 08:31
the workaround seems to work, so closing till a cleaner solution in the library is available

**Closed by akpw** 2022-11-26 08:31 UTC

**Comment by jgoclawski** [comment] 2025-03-07 11:47
@akpw I know this took a while, but it is fixed upstream 🙈 See https://github.com/socialwifi/RouterOS-api/pull/104 

We did not use `latin-1` as the default encoding (like in the monkey patch in this project), because there isn't a good value that would fit all users. Instead, the users should be able to set their own encoding that will work best for them.
